<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>WestcoastCars.Web</RootNamespace>
    <UserSecretsId>ea20a42c-8a5d-4f70-aea8-7671362179b6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WestcoastCars.Contracts\WestcoastCars.Contracts.csproj" />
  </ItemGroup>

</Project>
