services:
  api:
    build:
      context: .
      dockerfile: westcoast-cars.api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=westcoast_cars_db;Uid=root;Pwd=${MYSQL_PASSWORD}
      - apiImageUrl=http://api:8080/images/
      - JwtSettings__Secret=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  auth-api:
    build:
      context: .
      dockerfile: westcoast-cars.auth/Api/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=auth-db;Port=3306;Database=westcoast_auth;Uid=root;Pwd=${MYSQL_PASSWORD}
      - JwtSettings__Secret=${JWT_SECRET}
      - AdminSettings__Password=${ADMIN_PASSWORD}
    volumes:
      - ./dpkeys:/app/keys
    depends_on:
      auth-db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: westcoast-cars.web/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ApiBaseUrl=http://api:8080
      - AuthApiBaseUrl=http://auth-api:8080
    depends_on:
      - api
      - auth-api
    volumes:
      - ./dpkeys:/app/keys

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=westcoast_cars_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=westcoast_auth
    volumes:
      - mysql_auth_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  mysql_auth_data:
