
services:
  # Servicio de la API
  api:
    build:
      context: .
      dockerfile: westcoast-cars.api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=westcoast_cars_db;Uid=root;Pwd=password
      - apiImageUrl=http://api:8080/images/
    depends_on:
      db:
        condition: service_healthy

  # Servicio del Frontend Web
  web:
    build:
      context: .
      dockerfile: westcoast-cars.web/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ApiBaseUrl=http://api:8080
    depends_on:
      - api
    volumes:
      - dataprotection_keys:/app/keys

  # Servicio de la Base de Datos (MySQL)
  db:
    image: mysql:8.0 # Usamos una versión específica en lugar de 'latest'
    container_name: westcoast-mysql
    environment:
      # AVISO: Usa un password seguro en un entorno real, idealmente desde un archivo .env
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=westcoast_cars_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
  dataprotection_keys: