<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WestcoastCars.Domain\WestcoastCars.Domain.csproj" />
    <ProjectReference Include="..\WestcoastCars.Contracts\WestcoastCars.Contracts.csproj" />
    <ProjectReference Include="..\WestcoastCars.Application\WestcoastCars.Application.csproj" />
    <ProjectReference Include="..\WestcoastCars.Infrastructure\WestcoastCars.Infrastructure.csproj" />
    <ProjectReference Include="..\WestcoastCars.Api\WestcoastCars.Api.csproj" />
    <ProjectReference Include="..\WestcoastCars.Web\WestcoastCars.Web.csproj" />
  </ItemGroup>

</Project>
