// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WestcoastCars.Infrastructure.Data;

#nullable disable

namespace WestcoastCars.Infrastructure.Migrations;

[DbContext(typeof(WestcoastCarsContext))]
partial class WestcoastCarsContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

        modelBuilder.HasPostgresExtension("citext");
        modelBuilder.HasPostgresExtension("pg_trgm");

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex");
            b.ToTable("AspNetRoles");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
        {
            b.Property<string>("Id").HasColumnType("text");
            b.Property<int>("AccessFailedCount").HasColumnType("integer");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("text");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("boolean");
            b.Property<bool>("LockoutEnabled").HasColumnType("boolean");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("timestamp with time zone");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("PasswordHash").HasColumnType("text");
            b.Property<string>("PhoneNumber").HasColumnType("text");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("boolean");
            b.Property<string>("SecurityStamp").HasColumnType("text");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("boolean");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("character varying(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex");
            b.ToTable("AspNetUsers");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<string>("RoleId").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("RoleId");
            b.ToTable("AspNetRoleClaims");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("text");
            b.Property<string>("ClaimValue").HasColumnType("text");
            b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserClaims");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("text");
            b.Property<string>("ProviderKey").HasColumnType("text");
            b.Property<string>("ProviderDisplayName").HasColumnType("text");
            b.Property<string>("UserId").IsRequired().HasColumnType("text");
            b.HasKey("LoginProvider", "ProviderKey");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserLogins");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("text");
            b.Property<string>("RoleId").HasColumnType("text");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("AspNetUserRoles");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("text");
            b.Property<string>("LoginProvider").HasColumnType("text");
            b.Property<string>("Name").HasColumnType("text");
            b.Property<string>("Value").HasColumnType("text");
            b.HasKey("UserId", "LoginProvider", "Name");
            b.ToTable("AspNetUserTokens");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.FuelType", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasColumnType("citext");
            b.Property<DateTime>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique().HasDatabaseName("IX_FuelTypes_Name");
            b.ToTable("FuelTypes");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.Manufacturer", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.Property<DateTime>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Name").HasDatabaseName("IX_Manufacturers_Name_Trgm").HasMethod("GIN").HasOperators("gin_trgm_ops");
            b.ToTable("Manufacturers");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.ServiceBooking", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime>("BookingDate").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<string>("CustomerEmail").IsRequired().HasColumnType("text");
            b.Property<string>("CustomerName").IsRequired().HasColumnType("text");
            b.Property<string>("CustomerPhone").IsRequired().HasColumnType("text");
            b.Property<string>("Description").IsRequired().HasColumnType("text");
            b.Property<string>("ServiceType").IsRequired().HasColumnType("text");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<DateTime>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<int?>("VehicleId").HasColumnType("integer");
            b.Property<string>("VehicleRegistrationNumber").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.HasIndex("VehicleId");
            b.ToTable("ServiceBookings");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.TransmissionType", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<string>("Name").IsRequired().HasColumnType("citext");
            b.Property<DateTime>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique().HasDatabaseName("IX_TransmissionTypes_Name");
            b.ToTable("TransmissionTypes");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.Vehicle", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("City").HasColumnType("text");
            b.Property<string>("Color").HasColumnType("text");
            b.Property<DateTime>("CreatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<string>("Description").IsRequired().HasColumnType("text");
            b.Property<string>("ExternalListingId").HasColumnType("text");
            b.Property<int>("FuelTypeId").HasColumnType("integer");
            b.Property<string>("ImageUrl").IsRequired().HasColumnType("text");
            b.Property<DateTime?>("ImportedAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsSold").HasColumnType("boolean");
            b.Property<int>("ManufacturerId").HasColumnType("integer");
            b.Property<int>("Mileage").HasColumnType("integer");
            b.Property<string>("Model").IsRequired().HasColumnType("text");
            b.Property<int>("ModelYear").HasColumnType("integer");
            b.Property<DateTime?>("PublishedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("RegistrationNumber").IsRequired().HasColumnType("citext");
            b.Property<string>("Source").HasColumnType("text");
            b.Property<string>("SourceUrl").HasColumnType("text");
            b.Property<int>("TransmissionTypeId").HasColumnType("integer");
            b.Property<DateTime>("UpdatedAt").HasDefaultValueSql("NOW()").HasColumnType("timestamp with time zone");
            b.Property<int>("Price").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("ExternalListingId");
            b.HasIndex("FuelTypeId");
            b.HasIndex("IsSold");
            b.HasIndex("ManufacturerId");
            b.HasIndex("Model").HasDatabaseName("IX_Vehicles_Model").HasMethod("GIN").HasOperators("gin_trgm_ops");
            b.HasIndex("RegistrationNumber").IsUnique().HasDatabaseName("IX_Vehicles_RegistrationNumber");
            b.HasIndex("Source");
            b.HasIndex("TransmissionTypeId");
            b.ToTable("Vehicles");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired());

        modelBuilder.Entity("WestcoastCars.Domain.Entities.ServiceBooking", b =>
        {
            b.HasOne("WestcoastCars.Domain.Entities.Vehicle", "Vehicle").WithMany("ServiceBookings").HasForeignKey("VehicleId").OnDelete(DeleteBehavior.SetNull);
            b.Navigation("Vehicle");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.Vehicle", b =>
        {
            b.HasOne("WestcoastCars.Domain.Entities.FuelType", "FuelType").WithMany("Vehicles").HasForeignKey("FuelTypeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("WestcoastCars.Domain.Entities.Manufacturer", "Manufacturer").WithMany("Vehicles").HasForeignKey("ManufacturerId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("WestcoastCars.Domain.Entities.TransmissionType", "TransmissionType").WithMany("Vehicles").HasForeignKey("TransmissionTypeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("FuelType");
            b.Navigation("Manufacturer");
            b.Navigation("TransmissionType");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.FuelType", b => b.Navigation("Vehicles"));
        modelBuilder.Entity("WestcoastCars.Domain.Entities.Manufacturer", b => b.Navigation("Vehicles"));
        modelBuilder.Entity("WestcoastCars.Domain.Entities.TransmissionType", b => b.Navigation("Vehicles"));
        modelBuilder.Entity("WestcoastCars.Domain.Entities.Vehicle", b => b.Navigation("ServiceBookings"));
#pragma warning restore 612, 618
    }
}
