// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WestcoastCars.Infrastructure.Data;

#nullable disable

namespace WestcoastCars.Infrastructure.Migrations;

[DbContext(typeof(WestcoastCarsContext))]
partial class WestcoastCarsContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

        modelBuilder.Entity("WestcoastCars.Domain.Entities.FuelType", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("FuelTypes");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.Manufacturer", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("Manufacturers");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.OutboxMessage", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Content").IsRequired().HasColumnType("text");
            b.Property<string>("Error").HasColumnType("text");
            b.Property<DateTime>("OccurredOnUtc").HasColumnType("timestamp with time zone");
            b.Property<DateTime?>("ProcessedOnUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Type").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("OutboxMessages");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.ServiceBooking", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<DateTime>("BookingDate").HasColumnType("timestamp with time zone");
            b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("CustomerEmail").IsRequired().HasColumnType("text");
            b.Property<string>("CustomerName").IsRequired().HasColumnType("text");
            b.Property<string>("CustomerPhone").IsRequired().HasColumnType("text");
            b.Property<string>("Description").IsRequired().HasColumnType("text");
            b.Property<string>("ServiceType").IsRequired().HasColumnType("text");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<string>("VehicleRegistrationNumber").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("ServiceBookings");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.TransmissionType", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("Name").IsRequired().HasColumnType("text");
            b.HasKey("Id");
            b.ToTable("TransmissionTypes");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.Vehicle", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
            b.Property<string>("City").HasColumnType("text");
            b.Property<string>("Color").HasColumnType("text");
            b.Property<string>("Description").IsRequired().HasColumnType("text");
            b.Property<string>("ExternalListingId").HasColumnType("text");
            b.Property<int>("FuelTypeId").HasColumnType("integer");
            b.Property<string>("ImageUrl").IsRequired().HasColumnType("text");
            b.Property<DateTime?>("ImportedAt").HasColumnType("timestamp with time zone");
            b.Property<bool>("IsSold").HasColumnType("boolean");
            b.Property<int>("ManufacturerId").HasColumnType("integer");
            b.Property<int>("Mileage").HasColumnType("integer");
            b.Property<string>("Model").IsRequired().HasColumnType("text");
            b.Property<string>("ModelYear").IsRequired().HasColumnType("text");
            b.Property<DateTime?>("PublishedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("RegistrationNumber").HasColumnType("text");
            b.Property<string>("Source").HasColumnType("text");
            b.Property<string>("SourceUrl").HasColumnType("text");
            b.Property<int>("TransmissionTypeId").HasColumnType("integer");
            b.Property<int>("Value").HasColumnType("integer");
            b.HasKey("Id");
            b.HasIndex("ExternalListingId");
            b.HasIndex("FuelTypeId");
            b.HasIndex("ManufacturerId");
            b.HasIndex("Source");
            b.HasIndex("TransmissionTypeId");
            b.ToTable("Vehicles");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.Vehicle", b =>
        {
            b.HasOne("WestcoastCars.Domain.Entities.FuelType", "FuelType").WithMany("Vehicles").HasForeignKey("FuelTypeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("WestcoastCars.Domain.Entities.Manufacturer", "Manufacturer").WithMany("Vehicles").HasForeignKey("ManufacturerId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("WestcoastCars.Domain.Entities.TransmissionType", "TransmissionType").WithMany("Vehicles").HasForeignKey("TransmissionTypeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("FuelType");
            b.Navigation("Manufacturer");
            b.Navigation("TransmissionType");
        });

        modelBuilder.Entity("WestcoastCars.Domain.Entities.FuelType", b => b.Navigation("Vehicles"));
        modelBuilder.Entity("WestcoastCars.Domain.Entities.Manufacturer", b => b.Navigation("Vehicles"));
        modelBuilder.Entity("WestcoastCars.Domain.Entities.TransmissionType", b => b.Navigation("Vehicles"));
#pragma warning restore 612, 618
    }
}
